### ISSUE TITLE
Se deberían evitar las constantes mágicas

### ISSUE THREAD

**Issue by evolentini** [ctrinidad-ghub/TP3_TSSE#1]
https://github.com/ctrinidad-ghub/TP3_TSSE/blob/64ac3c6c6035e1b5b87f30c1445cc3eb023ed7c2/src/leds.c#L12

**Comment by ctrinidad-ghub** [comment]
Se reemplazó el valor 16 y el -1 por defines

**Comment by evolentini** [comment]
Perfecto, tenes la nota máxima en el TP3
